import Foundation
import CoreLocation

struct GeoCoordinate: Hashable, Codable {
    var latitude: Double
    var longitude: Double

    init(latitude: Double, longitude: Double) {
        self.latitude = latitude
        self.longitude = longitude
    }

    init(_ coordinate: CLLocationCoordinate2D) {
        self.latitude = coordinate.latitude
        self.longitude = coordinate.longitude
    }

    var clCoordinate: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
}

struct Vector2D: Hashable, Codable {
    var x: Double
    var y: Double

    var magnitude: Double { sqrt((x * x) + (y * y)) }

    func normalized() -> Vector2D {
        let mag = magnitude
        guard mag > 1e-9 else { return Vector2D(x: 0, y: 0) }
        return Vector2D(x: x / mag, y: y / mag)
    }

    static func +(lhs: Vector2D, rhs: Vector2D) -> Vector2D {
        Vector2D(x: lhs.x + rhs.x, y: lhs.y + rhs.y)
    }

    static func -(lhs: Vector2D, rhs: Vector2D) -> Vector2D {
        Vector2D(x: lhs.x - rhs.x, y: lhs.y - rhs.y)
    }

    static func *(lhs: Vector2D, rhs: Double) -> Vector2D {
        Vector2D(x: lhs.x * rhs, y: lhs.y * rhs)
    }

    func dot(_ other: Vector2D) -> Double {
        (x * other.x) + (y * other.y)
    }
}

enum RaceDirection: String, CaseIterable, Identifiable, Codable {
    case clockwise = "Clockwise"
    case counterClockwise = "Counterclockwise"

    var id: String { rawValue }
}

struct StartFinishGate: Hashable, Codable {
    var pointA: GeoCoordinate
    var pointB: GeoCoordinate
    var expectedForward: Vector2D

    var center: GeoCoordinate {
        GeoCoordinate(
            latitude: (pointA.latitude + pointB.latitude) / 2.0,
            longitude: (pointA.longitude + pointB.longitude) / 2.0
        )
    }

    static func autoGenerated(center: GeoCoordinate, headingDegrees: Double, widthMeters: Double) -> StartFinishGate {
        let forward = Geometry.headingToVector(headingDegrees).normalized()
        let perpendicular = Vector2D(x: -forward.y, y: forward.x).normalized()
        let halfWidth = max(1.0, widthMeters) / 2.0

        let a = Geometry.localPointToCoordinate(
            origin: center,
            point: perpendicular * halfWidth
        )
        let b = Geometry.localPointToCoordinate(
            origin: center,
            point: perpendicular * -halfWidth
        )

        return StartFinishGate(pointA: a, pointB: b, expectedForward: forward)
    }
}

struct RecordingConfig: Hashable, Codable {
    var track: Track
    var raceDirection: RaceDirection
    var gate: StartFinishGate
    var cooldownSeconds: TimeInterval
    var minimumLapDurationSeconds: TimeInterval
    var minimumSpeedMPS: Double
    var maximumHorizontalAccuracyMeters: Double
    var directionAlignmentThreshold: Double
}

struct TelemetrySample: Hashable {
    let coordinate: GeoCoordinate
    let timestamp: Date
    let speedMPS: Double
    let courseDegrees: Double?
    let horizontalAccuracyMeters: Double
    let accelerationX: Double?
    let accelerationY: Double?
    let accelerationZ: Double?
    let yawRate: Double?
}

struct LapTelemetrySummary: Hashable {
    let maxLongitudinalAccel: Double
    let maxLateralAccel: Double
    let maxYawRate: Double
    let averageSpeedMPS: Double
    let peakSpeedMPS: Double
    let distanceMeters: Double
    let sampleCount: Int
}

struct RecordedLap: Identifiable, Hashable {
    let id = UUID()
    let number: Int
    let durationSeconds: TimeInterval
    let crossedAt: Date
    let speedAtCrossingMPS: Double
    let telemetry: LapTelemetrySummary
    let route: [GeoCoordinate]
}

struct RecordedGateCrossing: Identifiable, Hashable {
    let id = UUID()
    let number: Int
    let crossedAt: Date
    let speedAtCrossingMPS: Double
}

enum Geometry {
    private static let earthRadiusMeters = 6_378_137.0

    static func headingToVector(_ headingDegrees: Double) -> Vector2D {
        let radians = headingDegrees * .pi / 180.0
        return Vector2D(x: sin(radians), y: cos(radians))
    }

    static func coordinateToLocalPoint(origin: GeoCoordinate, coordinate: GeoCoordinate) -> Vector2D {
        let lat0 = origin.latitude * .pi / 180.0
        let dLat = (coordinate.latitude - origin.latitude) * .pi / 180.0
        let dLon = (coordinate.longitude - origin.longitude) * .pi / 180.0

        return Vector2D(
            x: earthRadiusMeters * dLon * cos(lat0),
            y: earthRadiusMeters * dLat
        )
    }

    static func localPointToCoordinate(origin: GeoCoordinate, point: Vector2D) -> GeoCoordinate {
        let lat0 = origin.latitude * .pi / 180.0
        let dLat = point.y / earthRadiusMeters
        let dLon = point.x / (earthRadiusMeters * max(0.01, cos(lat0)))

        return GeoCoordinate(
            latitude: origin.latitude + (dLat * 180.0 / .pi),
            longitude: origin.longitude + (dLon * 180.0 / .pi)
        )
    }

    static func segmentsIntersect(_ p1: Vector2D, _ p2: Vector2D, _ q1: Vector2D, _ q2: Vector2D) -> Bool {
        let r = p2 - p1
        let s = q2 - q1
        let denominator = cross(r, s)
        let qMinusP = q1 - p1

        if abs(denominator) < 1e-9 {
            return false
        }

        let t = cross(qMinusP, s) / denominator
        let u = cross(qMinusP, r) / denominator

        return (0.0 ... 1.0).contains(t) && (0.0 ... 1.0).contains(u)
    }

    static func cross(_ a: Vector2D, _ b: Vector2D) -> Double {
        (a.x * b.y) - (a.y * b.x)
    }
}
